# Docker Compose

version: '3'

services:
  mysql:
    container_name: myboard-mysql
    image: mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: myboard
      MYSQL_USER: ${LOCAL_MYSQL_USER}
      MYSQL_PASSWORD: ${LOCAL_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${LOCAL_MYSQL_ROOT_PASSWORD}
      TZ: Asia/Seoul
    volumes:
      - ${LOCAL_MYSQL_VOLUME_PATH}:/var/lib/mysql
    ports:
      - ${LOCAL_MYSQL_PORT}:3306